class NewDevice {
  String owner,
      user,
      deviceName,
      deviceId,
      P1,
      P2,
      P3,
      P4,
      P5,
      P1Title,
      P2Title,
      P3Title,
      P4Title,
      P5Title,
      P1Widget,
      P2Widget,
      P3Widget,
      P4Widget,
      P5Widget;

  double minGaugeValP1,
      maxGaugeValP1,
      minGaugeValP2,
      maxGaugeValP2,
      minGaugeValP3,
      maxGaugeValP3,
      minGaugeValP4,
      maxGaugeValP4,
      minGaugeValP5,
      maxGaugeValP5;

  NewDevice(
      {required this.owner,
      required this.user,
      required this.deviceName,
      required this.deviceId,
      required this.minGaugeValP1,
      required this.maxGaugeValP1,
      required this.minGaugeValP2,
      required this.maxGaugeValP2,
      required this.minGaugeValP3,
      required this.maxGaugeValP3,
      required this.minGaugeValP4,
      required this.maxGaugeValP4,
      required this.minGaugeValP5,
      required this.maxGaugeValP5,
      required this.P1,
      required this.P2,
      required this.P3,
      required this.P4,
      required this.P5,
      required this.P1Title,
      required this.P2Title,
      required this.P3Title,
      required this.P4Title,
      required this.P5Title,
      required this.P1Widget,
      required this.P2Widget,
      required this.P3Widget,
      required this.P4Widget,
      required this.P5Widget});
}
